#version 430 core

layout(local_size_x = 8,local_size_y = 8,local_size_z = 1)in;
layout(rgba32f, binding = 0) uniform image2D image;

uniform sampler2D sampler;
uniform vec2 u_res;
uniform float edge_thr;
shared int edges[64];
void main(){
	vec2 texel = 1.0 / u_res;
	vec2 uv = vec2(gl_GlobalInvocationID.xy) * texel;
	vec4 color = texture(sampler, uv);
	int dir;
	 if (vec4(1,0, 0, 1) == color){
		dir = 0;
	}
	else if (vec4(1,1, 0, 1) == color){
		dir = 1;
	}
	else if (vec4(0,0, 1, 1) == color){
		dir = 2;
	}
	else if (vec4(0,1, 0, 1) == color){
		dir = 3;
	}
	else{
		dir = -1;
	}
	edges[gl_LocalInvocationIndex] = dir;
	barrier();
	memoryBarrierShared();
	if (0 == gl_LocalInvocationIndex){
		int dir1[4] = {0, 0, 0, 0};
		int sum = 0;
		for (int i = 0; i < 64; ++i){
			if (edges[i] >= 0){
				++sum;
				++dir1[edges[i]];
			}
		}
		int _max = -1;int max_idx = -1;
		for (int i = 0; i < 4; ++i){
			if (dir1[i] > _max){
				_max = dir1[i];
				max_idx = i;
			}
		}
		if ((sum / 64.0f) < edge_thr){
			imageStore(image,ivec2(gl_WorkGroupID.xy),vec4(0, 0, 0, 0));
		}
		else{
		if (0 == max_idx){
			imageStore(image,ivec2(gl_WorkGroupID.xy),vec4(1,0, 0, 1));

		}
		else if (1 == max_idx){
			imageStore(image,ivec2(gl_WorkGroupID.xy),vec4(1,1, 0, 1));

		}
		else if (2 == max_idx){
			imageStore(image,ivec2(gl_WorkGroupID.xy),vec4(0,0, 1, 1));

		}
		else if (3 == max_idx){
			imageStore(image,ivec2(gl_WorkGroupID.xy),vec4(0,1, 0, 1));

		}

		}
	}
}